# Generated by Django 3.1.7 on 2021-03-31 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('CodeMat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NomMat', models.CharField(max_length=10)),
                ('Ue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcour', models.CharField(choices=[('MISS', 'MISS'), ('MF', 'MF'), ('ME', 'ME')], max_length=5)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteUser', models.FloatField(max_length=10)),
                ('Semestre', models.CharField(max_length=2)),
                ('Mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matieres')),
                ('Us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matieres',
            name='Parc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profil'),
        ),
    ]
