# Generated by Django 3.1.7 on 2021-04-01 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_profil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, default='student_male_64px.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='parcour',
            field=models.CharField(choices=[('MISS', 'MISS'), ('MF', 'MF'), ('ME', 'ME')], max_length=5, verbose_name='Choisissez Votre Parcours: '),
        ),
        migrations.AlterField(
            model_name='profil',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Choisissez Votre CE: '),
        ),
    ]
