# Generated by Django 3.1.7 on 2021-04-16 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20210401_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carte_etudiant', models.CharField(max_length=4, verbose_name="Carte d'étudiant")),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('Mention', models.CharField(choices=[('MA', 'Mathematique et Application'), ('PC', 'Physique Chimie'), ('PA', 'Physique Application'), ('SV', 'Science de la vie')], help_text='Choisir votre mention', max_length=30)),
                ('Parcour', models.CharField(choices=[('MISS', 'MISS'), ('MF', 'MF'), ('ME', 'ME')], help_text='Choisir votre parcours', max_length=30)),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/student_male_64px.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Choisissez Votre CE: '),
        ),
    ]
