# Generated by Django 3.1.7 on 2021-04-21 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210416_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unite_Ens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_UE', models.CharField(max_length=20)),
                ('Semestre', models.CharField(max_length=2)),
                ('Parc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profil', verbose_name='Parcour')),
            ],
        ),
        migrations.RemoveField(
            model_name='moyenneuser',
            name='UserMoy',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Mat',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Us',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='id',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='Carte_etudiant',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name="Carte d'étudiant"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^.{10}$')]),
        ),
        migrations.DeleteModel(
            name='Matieres',
        ),
        migrations.DeleteModel(
            name='MoyenneUser',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
