# Generated by Django 3.1.7 on 2021-04-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210421_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note_user',
            old_name='Validadation_UE',
            new_name='Validation_Semestre',
        ),
        migrations.RenameField(
            model_name='note_user',
            old_name='Validadation_semestre',
            new_name='Validation_UE',
        ),
    ]
