# Generated by Django 3.1.7 on 2021-04-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210421_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note_user',
            old_name='Note_User',
            new_name='Note',
        ),
    ]
